---
- hosts: node
  tasks:
   - name: Set authorized key
     authorized_key:
       user: sanket
       state: present
       key: "{{ lookup('file', '/home/sanket/.ssh/id_rsa.pub') }}"

   - name: Disable empty password login
     lineinfile: 
       path: /etc/ssh/sshd_config 
       regexp: '^#?PermitEmptyPasswords' 
       line: 'PermitEmptyPasswords no'
   
   - name: Disable remote root login
     lineinfile: 
       path: /etc/ssh/sshd_config 
       regexp: '^#?PermitRootLogin' 
       line: 'PermitRootLogin no'
 
   - name: Disable password login
     lineinfile: 
       path: /etc/ssh/sshd_config 
       regexp: '^#?PasswordAuthentication' 
       line: 'PasswordAuthentication no'

   - name: Enable PAM
     lineinfile: 
       path: /etc/ssh/sshd_config 
       regexp: '^#?UsePAM' 
       line: 'UsePAM yes'
